language: c
dist: bionic

notifications:
  email: false

env:
 - COMPAT=0 DEVELOPER=0 EXPERIMENTAL_FEATURES=0
 - COMPAT=0 DEVELOPER=0 EXPERIMENTAL_FEATURES=1
 - COMPAT=0 DEVELOPER=1 EXPERIMENTAL_FEATURES=0
 - COMPAT=0 DEVELOPER=1 EXPERIMENTAL_FEATURES=1
 - COMPAT=1 DEVELOPER=0 EXPERIMENTAL_FEATURES=0
 - COMPAT=1 DEVELOPER=0 EXPERIMENTAL_FEATURES=1
 - COMPAT=1 DEVELOPER=1 EXPERIMENTAL_FEATURES=0
 - COMPAT=1 DEVELOPER=1 EXPERIMENTAL_FEATURES=1

before_install:
  sudo apt-get install -y libsqlite3-dev gcc-4.8 gettext python python3 python3-mako net-tools zlib1g-dev libsodium-dev

script:
  .travis/build.sh
